# Generated by Django 4.2.2 on 2023-06-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='test_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='categry',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
