# Generated by Django 4.2.2 on 2023-06-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_test_datetime_alter_categry_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='test_datetime',
        ),
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
