# Generated by Django 4.2.2 on 2023-06-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_test_datetime_alter_news_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='catgory',
            new_name='category',
        ),
    ]
